### ISSUE TITLE
Set up application boilerplate

### ISSUE THREAD

**Issue by marcingolenia** [best-for-beast/app.bestforbeast.com#4]
Before starting feature development we should setup a basic application boilerplate. It should allow further development based on initial assumptions and technical decisions.

The boilerplate should include
- basic [Svelte](https://svelte.dev/) application
- development environment tools preconfigured (linting, formatting)
- styling strategy
- basic directory structure
- build scripts defined to work with [Vercel](https://vercel.com)

**Comment by sgraczyk** [comment]
Unfortunately, Vercel allows deployments only from private GitHub accounts. In https://github.com/best-for-beast/app.bestforbeast.com/pull/14 I've decided to try Netlify. Pricing and limits have to be verified.
