### ISSUE TITLE
📝 As a Pet Owner I want to easily add a new pet of mine so I can see it among rest of my pets and have my pet family complete

### ISSUE THREAD

**Issue by marcingolenia** [best-for-beast/app.bestforbeast.com#6]
## Acceptance Criteria
**GIVEN** pet list 
**WHEN** pet owner clicks add new pet
**THEN** A tile with editable form with fields: <Name> required, ```<Type> required, <Breed>, <Birthdate>, <Gender>, <Description>, <Photo>``` is added to pet list

**GIVEN** form ```<Name>, <Birthdate>, <Gender>, <Description>```
**WHEN** pet owner creates pet
**THEN** pet can be found in the pet list

Examples:
| Name | Type | Breed   | Birthdate    | Gender | Description ||
| -------- | ------ | --------   | --------------- | ----------- | ---------------| --------|
| Azor   | Dog  | Kundel | 12.12.2016 | Male      | Nice dog    |

Form draft (add required fields and buttons);
![Screenshot from 2020-11-17 21-24-36](https://user-images.githubusercontent.com/5363851/99523873-f3156c00-2997-11eb-89db-d0086e1f4f47.png)

**Comment by sgraczyk** [comment]
Consider unifying the format of User Story with https://github.com/best-for-beast/app.bestforbeast.com/issues/5. Alternatively, propose changes, nevertheless, I'd like us to keep the same format and convention.
